// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: DeleteBook.sql

package sqlc

import (
	"context"
)

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}
