// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Book struct {
	ID       string
	Title    string
	Author   string
	Lang     string
	Category string
	BoughtBy string
	ReadBy   sql.NullString
}
