// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: PostBook.sql

package sqlc

import (
	"context"
	"database/sql"
)

const postBook = `-- name: PostBook :exec
INSERT INTO books (id, title, author, lang, category, bought_by, read_by) VALUES($1, $2, $3, $4, $5, $6, $7)
`

type PostBookParams struct {
	ID       string
	Title    string
	Author   string
	Lang     string
	Category string
	BoughtBy string
	ReadBy   sql.NullString
}

func (q *Queries) PostBook(ctx context.Context, arg PostBookParams) error {
	_, err := q.db.ExecContext(ctx, postBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Lang,
		arg.Category,
		arg.BoughtBy,
		arg.ReadBy,
	)
	return err
}
