// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UpdateBook.sql

package sqlc

import (
	"context"
	"database/sql"
)

const updateBook = `-- name: UpdateBook :exec
UPDATE books 
SET title=$2, author=$3, lang=$4, category=$5, bought_by=$6, read_by=$7
WHERE id=$1
`

type UpdateBookParams struct {
	ID       string
	Title    string
	Author   string
	Lang     string
	Category string
	BoughtBy string
	ReadBy   sql.NullString
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.ExecContext(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Lang,
		arg.Category,
		arg.BoughtBy,
		arg.ReadBy,
	)
	return err
}
